/*
 *  RTIbuilder
 *  Copyright (C) 2008-11  Universidade do Minho and Cultural Heritage Imaging
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 3 as published
 *  by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package RTIbuilder.GUI;

import java.awt.Dimension;
import org.jdesktop.application.Action;

public class LPtrackerAboutBox extends javax.swing.JDialog {

    public LPtrackerAboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
/*
        javax.swing.JTextArea verbose = new javax.swing.JTextArea();
        java.awt.GridBagConstraints gridBagConstraints;
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(LPtrackerAboutBox.class);

        verbose.setText(resourceMap.getString("verbose.text")); // NOI18N
        verbose.setMinimumSize(new Dimension(300,300));
        //imageLabel.setName("verbose_about"); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().remove(imageLabel);
        getContentPane().add(verbose, gridBagConstraints);

        pack();*/

        getRootPane().setDefaultButton(closeButton);


    }

    @Action public void closeAboutBox() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Acknowledgemts = new javax.swing.JLabel();
        AcknowledgemtText = new javax.swing.JLabel();
        Credits = new javax.swing.JLabel();
        CreditsText = new javax.swing.JLabel();
        Programmers = new javax.swing.JLabel();
        ProgrammersText = new javax.swing.JLabel();
        Acknowledgemts1 = new javax.swing.JLabel();
        AcknowledgemtText1 = new javax.swing.JLabel();
        Acknowledgemts2 = new javax.swing.JLabel();
        AcknowledgemtText2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(LPtrackerAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(LPtrackerAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 373, 90, 30));

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setName("appTitleLabel"); // NOI18N
        getContentPane().add(appTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        appVersionLabel.setName("appVersionLabel"); // NOI18N
        getContentPane().add(appVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        appVendorLabel.setName("appVendorLabel"); // NOI18N
        getContentPane().add(appVendorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        appHomepageLabel.setName("appHomepageLabel"); // NOI18N
        getContentPane().add(appHomepageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N
        getContentPane().add(appDescLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 8, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        Acknowledgemts.setFont(resourceMap.getFont("Acknowledgemts.font")); // NOI18N
        Acknowledgemts.setText(resourceMap.getString("Acknowledgemts.text")); // NOI18N
        Acknowledgemts.setName("Acknowledgemts"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(Acknowledgemts, gridBagConstraints);

        AcknowledgemtText.setText(resourceMap.getString("AcknowledgemtText.text")); // NOI18N
        AcknowledgemtText.setName("AcknowledgemtText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel1.add(AcknowledgemtText, gridBagConstraints);

        Credits.setFont(resourceMap.getFont("Credits.font")); // NOI18N
        Credits.setText(resourceMap.getString("Credits.text")); // NOI18N
        Credits.setName("Credits"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(Credits, gridBagConstraints);

        CreditsText.setText(resourceMap.getString("CreditsText.text")); // NOI18N
        CreditsText.setName("CreditsText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel1.add(CreditsText, gridBagConstraints);

        Programmers.setFont(resourceMap.getFont("Programmers.font")); // NOI18N
        Programmers.setText(resourceMap.getString("Programmers.text")); // NOI18N
        Programmers.setName("Programmers"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(Programmers, gridBagConstraints);

        ProgrammersText.setText(resourceMap.getString("ProgrammersText.text")); // NOI18N
        ProgrammersText.setName("ProgrammersText"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel1.add(ProgrammersText, gridBagConstraints);

        Acknowledgemts1.setFont(resourceMap.getFont("Acknowledgemts1.font")); // NOI18N
        Acknowledgemts1.setText(resourceMap.getString("Acknowledgemts1.text")); // NOI18N
        Acknowledgemts1.setName("Acknowledgemts1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(Acknowledgemts1, gridBagConstraints);

        AcknowledgemtText1.setText(resourceMap.getString("AcknowledgemtText1.text")); // NOI18N
        AcknowledgemtText1.setName("AcknowledgemtText1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel1.add(AcknowledgemtText1, gridBagConstraints);

        Acknowledgemts2.setFont(resourceMap.getFont("Acknowledgemts2.font")); // NOI18N
        Acknowledgemts2.setText(resourceMap.getString("Acknowledgemts2.text")); // NOI18N
        Acknowledgemts2.setName("Acknowledgemts2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(Acknowledgemts2, gridBagConstraints);

        AcknowledgemtText2.setText(resourceMap.getString("AcknowledgemtText2.text")); // NOI18N
        AcknowledgemtText2.setName("AcknowledgemtText2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel1.add(AcknowledgemtText2, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 360, 350));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jScrollPane2.border.title"))); // NOI18N
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextPane1.setContentType(resourceMap.getString("jTextPane1.contentType")); // NOI18N
        jTextPane1.setEditable(false);
        jTextPane1.setText(resourceMap.getString("jTextPane1.text")); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 390));
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcknowledgemtText;
    private javax.swing.JLabel AcknowledgemtText1;
    private javax.swing.JLabel AcknowledgemtText2;
    private javax.swing.JLabel Acknowledgemts;
    private javax.swing.JLabel Acknowledgemts1;
    private javax.swing.JLabel Acknowledgemts2;
    private javax.swing.JLabel Credits;
    private javax.swing.JLabel CreditsText;
    private javax.swing.JLabel Programmers;
    private javax.swing.JLabel ProgrammersText;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
