mcc -m calib data_calib.m ima_read_calib.m click_calib.m go_calib_optim.m ...
    ext_calib.m reproject_calib.m analyse_error.m recomp_corner_calib.m ...
    add_suppress.m saving_calib.m loading_calib.m extrinsic_computation.m ...
    undistort_image.m export_calib_data.m show_calib_results.m planemat.m ...
    ext_calib2.m